name: clean_arch
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  change_app_package_name: ^1.4.0
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  intl: ^0.20.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
